/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.enkripsifilezal;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.Charset;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author LENOVO
 */
public class EnkripsiDekripsi extends javax.swing.JFrame {

    /**
     * Creates new form Enkripsi
     */
    
    EnkripsiFile enkrip = new EnkripsiFile();
    DekripsiFile dekrip = new DekripsiFile();
    
    File pesan;
    File kunci;
    File sandi;
    File kunci2;
    
    public EnkripsiDekripsi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pilihpesan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bacahasil = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        bacapesan = new javax.swing.JTextArea();
        enkripsi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pilihkunci = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelnotif = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        notif = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tombolgenkunci = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pilihsandi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        bacaterang = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        bacasandi = new javax.swing.JTextArea();
        dekripsi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pilihkunci1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        notif2 = new javax.swing.JTextArea();
        labelnotif1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        judul = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI ENKRIPSI DEKRIPSI ZAL");
        setResizable(false);

        jLabel1.setText("Input File yang akan dienkripsi");

        pilihpesan.setText("Pilih File Pesan");
        pilihpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihpesanActionPerformed(evt);
            }
        });

        bacahasil.setEditable(false);
        bacahasil.setColumns(20);
        bacahasil.setRows(5);
        jScrollPane1.setViewportView(bacahasil);

        bacapesan.setColumns(20);
        bacapesan.setRows(5);
        jScrollPane2.setViewportView(bacapesan);

        enkripsi.setText("ENKRIP GAN");
        enkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enkripsiActionPerformed(evt);
            }
        });

        jLabel2.setText("Input Kunci berupa file");

        pilihkunci.setText("Pilih Kunci");
        pilihkunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihkunciActionPerformed(evt);
            }
        });

        jLabel3.setText("Isi File Asli:");

        jLabel4.setText("Isi File enkripsi:");

        labelnotif.setText("Notif");

        notif.setEditable(false);
        notif.setColumns(20);
        notif.setRows(5);
        jScrollPane5.setViewportView(notif);

        jLabel13.setText("Belum Punya Kunci?");

        jLabel14.setText("Yuk Generate");

        tombolgenkunci.setText("Generate Kunci Disini");
        tombolgenkunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolgenkunciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(pilihpesan))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pilihkunci, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(enkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelnotif))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolgenkunci, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(enkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilihpesan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pilihkunci))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelnotif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tombolgenkunci)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enkripsi", jPanel1);

        jLabel5.setText("Input File yang akan dienkripsi");

        pilihsandi.setText("Pilih File Sandi");
        pilihsandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihsandiActionPerformed(evt);
            }
        });

        bacaterang.setEditable(false);
        bacaterang.setColumns(20);
        bacaterang.setRows(5);
        jScrollPane3.setViewportView(bacaterang);

        bacasandi.setColumns(20);
        bacasandi.setRows(5);
        jScrollPane4.setViewportView(bacasandi);

        dekripsi.setText("DEKRIP GAN");
        dekripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dekripsiActionPerformed(evt);
            }
        });

        jLabel6.setText("Input Kunci berupa file");

        pilihkunci1.setText("Pilih Kunci");
        pilihkunci1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihkunci1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Isi File Sandi:");

        jLabel8.setText("Isi File Terang:");

        notif2.setEditable(false);
        notif2.setColumns(20);
        notif2.setRows(5);
        jScrollPane6.setViewportView(notif2);

        labelnotif1.setText("Notif");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pilihsandi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pilihkunci1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(dekripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelnotif1))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilihsandi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pilihkunci1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(dekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelnotif1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Dekripsi", jPanel2);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Kenalin, aku Muhammad Novrizal Ghiffari");

        jLabel10.setText("Traveller | Programmer | Codebreaker");

        jLabel11.setText("Pringgasela, Lombok Timur");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Yuk Hubungi Aku di :");

        jButton1.setText("Github");

        jButton2.setText("Instagram");

        jButton3.setText("Telegram");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("About Saya xixi", jPanel3);

        judul.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        judul.setText("ENKRIPSI DEKRIPSI XOR FILE");

        nama.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nama.setText("Muhammad Novrizal Ghiffari | 181710140 | II RPLK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nama)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(judul)
                                .addGap(133, 133, 133))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihsandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihsandiActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showDialog(this, "Pilih");
        if (result == JFileChooser.APPROVE_OPTION) {
            sandi = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + sandi.getAbsolutePath());
            BufferedReader reader = null;
            try {
                reader = new BufferedReader(new FileReader(sandi));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(EnkripsiDekripsi.class.getName()).log(Level.SEVERE, null, ex);
            }
            StringBuilder sb = new StringBuilder();
            String line;
            try {
                while((line = reader.readLine())!= null){
                    sb.append(line+"\n");
                }
            } catch (IOException ex) {
                Logger.getLogger(EnkripsiDekripsi.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.bacasandi.setText(sb.toString());
        }
    }//GEN-LAST:event_pilihsandiActionPerformed

    private void pilihpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihpesanActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showDialog(this, "Pilih");
        if (result == JFileChooser.APPROVE_OPTION) {
            pesan = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + pesan.getAbsolutePath());
            BufferedReader reader = null;
            try {
                reader = new BufferedReader(new FileReader(pesan));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(EnkripsiDekripsi.class.getName()).log(Level.SEVERE, null, ex);
            }
            StringBuilder sb = new StringBuilder();
            String line;
            try {
                while((line = reader.readLine())!= null){
                    sb.append(line+"\n");
                }
            } catch (IOException ex) {
                Logger.getLogger(EnkripsiDekripsi.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.bacapesan.setText(sb.toString());
        }
    }//GEN-LAST:event_pilihpesanActionPerformed

    private void pilihkunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihkunciActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showDialog(this, "Pilih");
        if (result == JFileChooser.APPROVE_OPTION) {
            kunci = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + kunci.getAbsolutePath());
        }
    }//GEN-LAST:event_pilihkunciActionPerformed

    private void enkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enkripsiActionPerformed
        File hasil = new File(System.getProperty("user.dir") + "/files/copied/" + "enkrip_"+pesan.getName());
        try {
            enkrip.enkripsikuy(pesan, kunci, hasil);
        } catch (IOException ex) {
            Logger.getLogger(EnkripsiDekripsi.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader reader = null;
            try {
                reader = new BufferedReader(new FileReader(hasil));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(EnkripsiDekripsi.class.getName()).log(Level.SEVERE, null, ex);
            }
            StringBuilder sb = new StringBuilder();
            String line;
            try {
                while((line = reader.readLine())!= null){
                    sb.append(line+"\n");
                }
            } catch (IOException ex) {
                Logger.getLogger(EnkripsiDekripsi.class.getName()).log(Level.SEVERE, null, ex);
            }
        this.bacahasil.setText(sb.toString());
        this.notif.setText("Berhasil, Cek file enkripsi mu di " + hasil.getAbsolutePath());
    }//GEN-LAST:event_enkripsiActionPerformed

    private void dekripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dekripsiActionPerformed
        // TODO add your handling code here:
        File hasil2 = new File(System.getProperty("user.dir") + "/files/copied/" + "dekrip_"+pesan.getName());
        try {
            dekrip.dekipsikuy(sandi, kunci2, hasil2);
        } catch (IOException ex) {
            Logger.getLogger(EnkripsiDekripsi.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader reader = null;
            try {
                reader = new BufferedReader(new FileReader(hasil2));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(EnkripsiDekripsi.class.getName()).log(Level.SEVERE, null, ex);
            }
            StringBuilder sb = new StringBuilder();
            String line;
            try {
                while((line = reader.readLine())!= null){
                    sb.append(line+"\n");
                }
            } catch (IOException ex) {
                Logger.getLogger(EnkripsiDekripsi.class.getName()).log(Level.SEVERE, null, ex);
            }
        this.bacaterang.setText(sb.toString());
        this.notif2.setText("Berhasil, Cek file dekripsi mu di " + hasil2.getAbsolutePath());
    }//GEN-LAST:event_dekripsiActionPerformed

    private void tombolgenkunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolgenkunciActionPerformed
        // TODO add your handling code here:
        File genkey = new File(System.getProperty("user.dir") + "/kunci");
        byte[] array = new byte[1024]; // length is bounded by 7
        new Random().nextBytes(array);
        String generatedString = new String(array, Charset.forName("UTF-8"));
        try {
            OutputStream out = new FileOutputStream(genkey);
            try {
                out.write(generatedString.getBytes());
                out.close();
                this.notif.setText("Berhasil, generate kunci di " + genkey.getAbsolutePath());
            } catch (IOException ex) {
                Logger.getLogger(EnkripsiDekripsi.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(EnkripsiDekripsi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombolgenkunciActionPerformed

    private void pilihkunci1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihkunci1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showDialog(this, "Pilih");
        if (result == JFileChooser.APPROVE_OPTION) {
            kunci2 = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + kunci2.getAbsolutePath());
        }
    }//GEN-LAST:event_pilihkunci1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnkripsiDekripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnkripsiDekripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnkripsiDekripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnkripsiDekripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnkripsiDekripsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bacahasil;
    private javax.swing.JTextArea bacapesan;
    private javax.swing.JTextArea bacasandi;
    private javax.swing.JTextArea bacaterang;
    private javax.swing.JButton dekripsi;
    private javax.swing.JButton enkripsi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel labelnotif;
    private javax.swing.JLabel labelnotif1;
    private javax.swing.JLabel nama;
    private javax.swing.JTextArea notif;
    private javax.swing.JTextArea notif2;
    private javax.swing.JButton pilihkunci;
    private javax.swing.JButton pilihkunci1;
    private javax.swing.JButton pilihpesan;
    private javax.swing.JButton pilihsandi;
    private javax.swing.JButton tombolgenkunci;
    // End of variables declaration//GEN-END:variables
}
